name=input('what is your name?')
print('hellow', name)
age = input('what is your age?')
print('you are', age, 'years old')
hobby = input('what is your hobby?')
print('your hobby is', hobby)
adress = input('what is your address?')
print('your address is', adress)
goal = input('what is your goal?')
print('your goal is', goal)
