name=input('what is your name?')
age=input('what is your age?')
hobby=input('what is your hobby?')
grade=input('what is your grade?')
address = input('what is your address?')
goal_by_end_of_year = input('what is your goal by the end of this year?')
ultimate_goal = input('what is your ultimate goal?')
print('================================================================')
print('my info card')
print('================================================================')
print('hello', name)
print('you are', age, 'years old')
print('your hobby is', hobby)
print('your grade is', grade)
print('your address is', address)
print('your goal by the end of this year is', goal_by_end_of_year)
print('your ultimate goal is', ultimate_goal)
